#
# Mach Operating System
# Copyright (c) 1993 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon
# the rights to redistribute these changes.
#
#
# HISTORY
# $Log:	Makefile,v $
# Revision 2.6  93/03/09  17:55:46  danner
# 	Arrgh. Put exec.h back.
# 	[93/02/08            jfriedl]
# 
# Revision 2.5  93/02/04  18:21:33  mrt
# 	Removed varargs.h, exec.h, asm.h (now in m88k); added mouse.h
# 	[93/02/02            jfriedl]
# 
# 	Created for ODE make
# 	[92/12/17            mrt]
# 


VPATH		= ../../kernel/luna88k

INCLUDES	= exec.h lcd.h fb.h mouse.h

ILIST		= ${INCLUDES}

IDIR		= /include/luna88k/
.include <${RULES_MK}>


